### ISSUE TITLE
pagination for the blogs

### ISSUE THREAD

**Issue by MarcBessieres** [osmbe/website#16]
Have a maximum number of posts per page

**Comment by jbelien** [comment]
Well pagination + multilanguage will probably be a pain in the ass with the system of multi-language we chose...

I'm searching for the best way to handle multi-language.

**Comment by xivk** [comment]
The blogposts translate as long as they have the same file name except for the language tag. I would just ignore this related to pagination. Maybe even just jump to page 1 when switching language?

**Comment by jbelien** [comment]
See #37

**Comment by jbelien** [comment]
Apparently that's not possible to handle pagination with mutliple languages without something like https://github.com/scandio/jekyll-paginate-multiple but that plugin is not enable in GitHub pages (see https://pages.github.com/versions/).

The issue is that pagination count **every** post/pages without taking the language into account ; then you have "empty" pages.

There is probably a solution but I didn't find it (yet) :P
